import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { test } from "node:test";

const source = await readFile(new URL("./dashboard-client.tsx", import.meta.url), "utf8");

test("dashboard client keeps production account and document flows wired", () => {
  for (const marker of [
    "/auth/refresh",
    "/auth/logout",
    "/auth/demo",
    "/auth/request-password-reset",
    "/auth/request-email-verification",
    "Document center",
    "FileObjectRow",
    "FilePreviewLink",
    "requestContractUpload",
    "requestSignatureUpload",
    "requestVehicleFolderUpload",
    "requestCustomerFolderUpload",
    "/operations/rental-contract-events",
    "contractEventLabel",
    "contract-timeline",
    "FleetCore Command",
    "GlobalSearchResult",
    "globalSearchResults",
    "global-search-results",
    "search-result-row",
    "openSearchResult",
    "command-actions",
    "fleet-command-actions",
    "command-create-booking",
    "command-create-vehicle",
    "command-create-customer",
    "command-upload-document",
    "command-create-expense",
    "command-create-service",
    "command-share-contract",
    "OwnerProfileDialog",
    "fleetcore-profile-open",
    "/auth/team",
    "/auth/me",
    "saveProfilePhoto",
    "owner-photo-hint",
    "VehicleVisual",
    "vehicleVisualVariant",
    "saveVehiclePhoto",
    "removeVehiclePhoto",
    "photoUrl",
    "saveCompanyBranding",
    "saveCompanyLogo",
    "BookingCalendar",
    "Company branding",
    "/operations/rental-checklists",
    "createRentalChecklist",
    "checklist-cell",
    "/flow",
    "contractPdfUrl",
    "RentalFlowPanel",
    "RentalFlowHistoryPanel",
    "FinalSettlementPanel",
    "rental-flow-panel",
    "flow-history-panel",
    "flow-operations-grid",
    "settlement-panel",
    "flow-progress-row",
    "flow-control-grid",
    "flow-playbook",
    "История Rental Flow",
    "Финальный расчёт",
    "Депозит и финальный расчёт",
    "finalizeRentalFlow",
    "processFlowAction",
    "openRentalContractPdf",
    "auth-toolbar",
    "auth-demo-link",
    "auth-secondary-actions",
    "auth-preview-shell",
    "initialMode",
    "MobileDrawer",
    "mobile-drawer",
    "mobile-menu-button",
    "openVehicleCreate",
    "openCustomerCreate",
    "assignVehicleToNewCustomer",
    "customer-assign-vehicle",
    "ClientProfilePanel",
    "client-profile-panel",
    "Client CRM",
    "Добавить авто клиенту",
    "openRentalContractPdfForRental",
    "OnboardingWizard",
    "fleetcore-onboarding-open",
    "DocumentVault",
    "document-vault",
    "document-hub-pivots",
    "document-center-board",
    "document-status-board",
    "rental-folder-card",
    "Папки аренды",
    "TodayOperationsDashboard",
    "today-operations-board",
    "today-task-board",
    "Что делать сегодня",
    "operations-queue",
    "Рабочий центр автопарка",
    "RentalDetailPanel",
    "rental-detail-panel",
    "rental-step-master",
    "rental-detail-timeline",
    "rental-health-strip",
    "Следующее лучшее действие",
    "client-priority-card",
    "rental-flow-plus",
    "Rental Flow Plus",
    "Финальный расчёт",
    "document-workbench-grid",
    "mapProvider",
    "apple-map-panel",
    "apple-map-canvas",
    "mobile-fab",
    "SectionFocusBar",
    "section-focus-bar",
    "Следующее действие раздела",
    "operation-auto-context",
    "Создать автомобиль автоматически",
    "Создать инвойс автоматически",
    "RentalScenarioWizard",
    "rental-scenario-wizard",
    "Новая аренда с нуля",
    "runRentalWizardStep",
    "shareRentalContract",
    "ShareContractDialog",
    "DocumentPreviewDialog",
    "document-preview-modal",
    "share-channel-grid",
    "openTelegram",
    "openEmail",
    "sidebar-signout-button",
    "mobile-drawer-signout",
    "Файл не выбран",
    "Фото профиля не выбрано",
    "Нет активного Rental Flow",
    "Rental Flow уже завершен",
    "Сессия не найдена",
  ]) {
    assert.match(source, new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  }
});

test("dashboard client does not ship inert buttons", () => {
  const buttonTags = source.match(/<button\b[\s\S]*?>/g) ?? [];

  assert.ok(buttonTags.length > 20, "expected dashboard buttons to be present");

  for (const tag of buttonTags) {
    const hasAction = /onClick=/.test(tag) || /type="submit"/.test(tag);
    assert.ok(hasAction, `button without click handler or submit type: ${tag}`);
  }

  assert.doesNotMatch(source, /MobileAppNav|mobile-app-nav|mobile-account-strip/);
  assert.doesNotMatch(source, /openExternalMap|maps\.apple\.com|google\.com\/maps\/search/);
});
