import type { FastifyPluginAsync } from "fastify";
import { createRental, getCompany, getRental, getRentalFlow, hasRentalReferences, listRentals, returnRental, updateRental } from "../db/repositories.js";
import { getTenantScope, requireRoles } from "../lib/access-control.js";
import { envelope } from "../lib/http.js";
import { rentalInput, rentalPatchInput, rentalReturnInput } from "../schemas.js";

function pdfEscape(value: string) {
  return value.replaceAll("\\", "\\\\").replaceAll("(", "\\(").replaceAll(")", "\\)");
}

function textLine(value: string, x: number, y: number, size = 10) {
  return `BT /F1 ${size} Tf ${x} ${y} Td (${pdfEscape(value.slice(0, 110))}) Tj ET`;
}

function buildSimplePdf(lines: string[]) {
  const content = [
    "0.08 w",
    "48 760 500 1 re f",
    textLine("FleetCore Rental Agreement", 54, 780, 18),
    ...lines.flatMap((line, index) => textLine(line, 54, 735 - index * 18, index === 0 ? 13 : 10)),
  ].join("\n");
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    `<< /Length ${Buffer.byteLength(content)} >>\nstream\n${content}\nendstream`,
  ];
  let body = "%PDF-1.4\n";
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(Buffer.byteLength(body));
    body += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });
  const xrefOffset = Buffer.byteLength(body);
  body += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  body += offsets.slice(1).map((offset) => `${String(offset).padStart(10, "0")} 00000 n \n`).join("");
  body += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return Buffer.from(body);
}

export const rentalRoutes: FastifyPluginAsync = async (app) => {
  app.get("/rentals", async (request) => envelope(await listRentals(getTenantScope(request))));

  app.get("/rentals/:rentalId", async (request, reply) => {
    const { rentalId } = request.params as { rentalId: string };
    const rental = await getRental(getTenantScope(request), rentalId);
    if (!rental) {
      return reply.code(404).send({ error: "Rental not found" });
    }

    return envelope(rental);
  });

  app.get("/rentals/:rentalId/flow", async (request, reply) => {
    const { rentalId } = request.params as { rentalId: string };
    const flow = await getRentalFlow(getTenantScope(request), rentalId);
    if (!flow) {
      return reply.code(404).send({ error: "Rental flow not found" });
    }

    return envelope(flow);
  });

  app.get("/rentals/:rentalId/contract.pdf", async (request, reply) => {
    const { rentalId } = request.params as { rentalId: string };
    const scope = getTenantScope(request);
    const [company, flow] = await Promise.all([
      getCompany(scope, scope.companyId),
      getRentalFlow(scope, rentalId),
    ]);
    if (!company || !flow) {
      return reply.code(404).send({ error: "Rental contract not found" });
    }

    const lines = [
      `${company.tradingName} · ${company.legalName}`,
      `Company address: ${company.businessAddress ?? company.country}`,
      `Tax ID: ${company.taxId ?? "-"} · Billing: ${company.billingEmail ?? "-"}`,
      `Contract / Rental ID: ${flow.rental.id}`,
      `Customer: ${flow.customer.displayName} · ${flow.customer.email} · ${flow.customer.phone}`,
      `Vehicle: ${flow.vehicle.make} ${flow.vehicle.model} ${flow.vehicle.year} · Plate ${flow.vehicle.plateNumber} · VIN ${flow.vehicle.vin}`,
      `Pickup: ${new Date(flow.rental.pickupAt).toISOString()}`,
      `Return: ${new Date(flow.rental.returnAt).toISOString()}`,
      `Rental total: ${flow.rental.totalAmount} ${company.currency}`,
      `Deposit: ${flow.rental.depositAmount} ${company.currency}`,
      `Payment collected: ${flow.paidAmount} ${company.currency}`,
      `Contract status: ${flow.contract?.status ?? "draft"}`,
      `Pickup checklist: ${flow.checklists.some((item) => item.phase === "pickup") ? "completed" : "pending"}`,
      `Return checklist: ${flow.checklists.some((item) => item.phase === "return") ? "completed" : "pending"}`,
      "Terms: customer accepts the vehicle in good condition and returns it at the agreed time.",
      "Customer signature: __________________________",
      "Company signature: ___________________________",
      company.contractFooter ?? "Generated by FleetCore SaaS.",
    ];
    const pdf = buildSimplePdf(lines);
    reply.header("content-type", "application/pdf");
    reply.header("content-length", String(pdf.byteLength));
    reply.header("content-disposition", `inline; filename="rental-contract-${rentalId}.pdf"`);
    return reply.send(pdf);
  });

  app.post("/rentals", async (request, reply) => {
    if (!requireRoles(request, reply, ["owner", "admin", "fleet_manager"])) return;

    const parsed = rentalInput.safeParse(request.body);
    if (!parsed.success) {
      return reply.code(400).send({ error: "Invalid rental payload", issues: parsed.error.flatten() });
    }

    const scope = getTenantScope(request);
    if (!(await hasRentalReferences(scope, parsed.data.customerId, parsed.data.vehicleId))) {
      return reply.code(422).send({ error: "Customer or vehicle does not exist" });
    }

    const rental = await createRental(scope, parsed.data);

    return reply.code(201).send(envelope(rental));
  });

  app.patch("/rentals/:rentalId", async (request, reply) => {
    if (!requireRoles(request, reply, ["owner", "admin", "fleet_manager"])) return;

    const { rentalId } = request.params as { rentalId: string };
    const parsed = rentalPatchInput.safeParse(request.body);
    if (!parsed.success) {
      return reply.code(400).send({ error: "Invalid rental payload", issues: parsed.error.flatten() });
    }

    const scope = getTenantScope(request);
    if (!(await hasRentalReferences(scope, parsed.data.customerId, parsed.data.vehicleId))) {
      return reply.code(422).send({ error: "Customer or vehicle does not exist" });
    }

    const rental = await updateRental(scope, rentalId, parsed.data);
    if (!rental) {
      return reply.code(404).send({ error: "Rental not found" });
    }

    return envelope(rental);
  });

  app.post("/rentals/:rentalId/return", async (request, reply) => {
    if (!requireRoles(request, reply, ["owner", "admin", "fleet_manager"])) return;

    const { rentalId } = request.params as { rentalId: string };
    const parsed = rentalReturnInput.safeParse(request.body);
    if (!parsed.success) {
      return reply.code(400).send({ error: "Invalid return payload", issues: parsed.error.flatten() });
    }

    const rental = await returnRental(getTenantScope(request), rentalId, parsed.data);
    if (!rental) {
      return reply.code(404).send({ error: "Rental not found or cannot be returned" });
    }

    return envelope(rental);
  });
};
